### PR TITLE
add qflist function

### PR DESCRIPTION
**Pull request by chrisbra**
P-R on branch 1.3 as requested

### CODE REVIEW

**Comment by dyng** [comment]
Thank you for your contribution, it will be merged to `master` in next release.

**Comment by dyng** [comment]
I found a problem that if you open a file in location list, that file's buffer will be opened in CtrlSF's window and replace CtrlSF, I think that is not what a user expects.

How are you using location list in CtrlSF? Just as an overview of matches?

**Comment by vim-ml** [comment]
Thanks. Yes, usually as an overview, but is it a problem, if the files are opened in the CtrlSF Window? Else we would have to use a quickfixlist and then make sure not to overwrite an already opened list. So one would need a configuration parameter or extra command to fill the quickfix list

**Comment by dyng** [comment]
CtrlSF's window is configured for CtrlSF only (it's a half-window sized and width & height fixed), I think it is some what counter-intuitive that opening a file here. But I'll leave it this way for a while, to see if we need to implement a dedicated overview window.

Agreed on what you said about quickfix. I have implemented the quicklist part in the latest commit of `v1.3`, with an option to toggle it.

And I also change the map key of `llist` to `loclist`, please update your configuration. I'm sorry for this inconvenience.

**Comment by chrisbra** [comment]
alright. Thanks

**Pull request merged**
