### PR TITLE
:CtrlSFFromExternal command and function

### PR DESCRIPTION
**Pull request by jesseleite**
See #252 for concept.  Still WIP.

### CODE REVIEW

**Comment by jesseleite** [comment]
I'm able to get my own ag output into CtrlSF with this, but...

- It doesn't highlight the pattern, because it doesn't know about the pattern yet.
- Compact mode is pretty messed up, and is showing every line including surrounding context 🤔

**Comment by jesseleite** [comment]
Oh interesting.  I can't seem to get the highlighting, even though I'm passing the same arguments to `ag` as you are (copied from your source code, and I see them in debug mode too).  For testing purposes, this is what I've got...

```vim
function! agriculture#fzf_ag_raw_into_ctrlsf(command_suffix, ...)
  let g:testing_ag = system('ag -C 3 --nofollow --noheading --nogroup --nocolor --nobreak '.a:command_suffix)
  echo 'output set to g:testing_ag'
endfunction
```

Then running `:CtrlSFFromExternal g:testing_ag`, no highlighting.  I'm noticing `HighlightRegex` is empty though.  I'll have to dig into the source more later.

I appreciate your help so far btw!  Thank you!

**Comment by dyng** [comment]
Please take a look at `ctrlsf#opt#ParseOptions()`, CtrlSF got highlighting pattern within this function.

**Comment by dyng** [comment]
Close this PR for a long period of inactive.

**Pull request closed without merging**
