### PR TITLE
support ag -w whole-word matching

### PR DESCRIPTION
**Pull request by sarrow104**

### CODE REVIEW

**Comment by dyng** [comment]
Can `\bword\b` meet your need? I'm trying my best not to introduce any backend-specific arguments.

**Comment by sarrow104** [comment]
backend tool ag does not support this feature. sad

**Comment by dyng** [comment]
```
$ cat /tmp/abc
test
testthis
testthat

$ ag -w 'test' /tmp/abc
1:test

$ ag '\btest\b' /tmp/abc
1:test

$ ag 'test' /tmp/abc
1:test
2:testthis
3:testthat
```

My test shows that `ag` does also support word boundary pattern `\b`.

**Comment by dyng** [comment]
But thank you for figuring out a trivial mistake of mine.

**Comment by sarrow104** [comment]
oh, i see. my poor bash syntax.

**Comment by sarrow104** [comment]
you should have a look at the diff window; there must be an error:

 " default values to options
@@ -62,7 +64,7 @@ func! ctrlsf#opt#GetOpt(name) abort
     if has_key(s:options, a:name)
         return s:options[a:name]
     else
-        return get(s:default, 'a:name', '')
+        return get(s:default, a:name, '')
     endif
 endf

**Comment by dyng** [comment]
Yes, I have fixed it. Thanks for you figuring it out!

**Pull request closed without merging**
