### PR TITLE
Feature/compact view

### PR DESCRIPTION
**Pull request by dyng**
Add a compact view for CtrlSF window, which is more familiar to user who loves quickfix window.

screen shot 2017-02-19 at 3 09 48 pm

- use `M` to switch CtrlSF window between 'norma' and 'compact' view.
- set compact view as default by `let g:ctrlsf_default_view_mode = 'compact'`.

Thanks to user @skamsie and @synic .

### CODE REVIEW

**Comment by dyng** [comment]
@synic @skamsie
Can you do me a favor to try and test this new feature for a while? Feel free to report any issue here.

@mkitt 
I have implemented a compact view of CtrlSF window, which has more features than plain quickfix window. Could you have a try on it and tell me if it meets your need? I also have a plan to make `CtrlSFQuickfix` commands deprecated, maybe in next major release.

**Comment by skamsie** [comment]
looks good 👍

**Comment by mkitt** [comment]
@dyng thanks for the heads up. Looks great 👍

**Comment by synic** [comment]
Just tried it out.  This is perfect!

**Pull request merged**
